--INSERT INTO users (username, password) VALUES ('1', '$2a$11$dp4wMyuqYE3KSwIyQmWZFeUb7jCsHAdk7ZhFc0qGw6i5J124imQBi');
--INSERT INTO users (username, password) VALUES ('2', '$2a$11$3NO32OV1TGjap3xMpAEjmuiizitWuaSwUYz42aMtlxRliwJ8zm4Sm');
--INSERT INTO auth_user_group (username, auth_group) VALUES('1', 'USER');
--INSERT INTO auth_user_group (username, auth_group) VALUES('1', 'ADMIN');
--INSERT INTO auth_user_group (username, auth_group) VALUES('2', 'USER');